# TODO-copier-package add notebooks to docs


rule docs_build:
    """
    Build the documentation.

    input:
        mkdocs_yml: WORKFLOW_BASE is used here instead of workflow.source_path()
            since workflow.source_path() cannot cache an entire directory
            so instead just point to the mkdocs.yml file and assume the
            worker has access to the entire directory
        dag_svg: The DAG SVG generated by the `dag_svg` rule.

    output:
        site_dir: The directory where the built documentation will be placed.
    """
    localrule: True
    input:

        mkdocs_yml=WORKFLOW_BASE / "../docs/mkdocs.yml",
        dag_svg=rules.dag_svg.output,
    output:
        site_dir=directory(Path(config["DOCS_SITE_DIR"]).resolve()),
    log:
        stdout=LOG_DIR / "docs_build" / "stdout.log",
        stderr=LOG_DIR / "docs_build" / "stderr.log",
    params:
        docs_assets="docs/docs/_assets",
    conda:
        get_localized_conda(config["CONDA"]["ENVS"]["DOCS"])
    shell:
        """
        exec 1>"{log.stdout}"
        exec 2>"{log.stderr}"
        export JUPYTER_PLATFORM_DIRS=1
        export DOCS_ASSETS_DIR="{params.docs_assets}"
        mkdocs build \
          --config-file {input.mkdocs_yml} \
          --site-dir {output.site_dir}
        """


# TODO-copier-package deploy docs with `mike`
# rule docs_deploy:
#     """
#     Deploy the documentation to the `gh-pages with
#     [mike](https://github.com/jimporter/mike?tab=readme-ov-file#building-your-docs).
#     """
#     input:
#         mkdocs_yml=(DOCS_DIR / "mkdocs.yml"),
#         dag_svg=rules.dag_svg.output,
#     log:
#         LOG_DIR / "docs.log",
#     conda:
#         get_localized_conda(config["CONDA"]["ENVS"]["DOCS"])
#     shell:
#         # TODO Configure versioning so `mike` grabs semantic tags
#         """
#         exec 1>"{log}"
#         exec 2>"{log}"
#         echo "TODO configure versioning"
#         exit 1
#         # mike deploy --config-file {input.mkdocs_yml}
#         """


# TODO-copier-package serve docs with `mike`
# rule docs_serve_mike:
#     """
#     Serve the documentation committed to the `gh-pages` branch
#     [using `mike`](https://github.com/jimporter/mike?tab=readme-ov-file#viewing-your-docs).
#     NOTE: This rule is "blocking", and will not return until the server is stopped.
#           This rule is only for development purposes.
#     """
#     input:
#         mkdocs_yml=(DOCS_DIR / "mkdocs.yml"),
#         dag_svg=rules.dag_svg.output,
#     log:
#         LOG_DIR / "docs_serve.log",
#     conda:
#         get_localized_conda(config["CONDA"]["ENVS"]["DOCS"])
#     shell:
#         """
#         exec 1>"{log}"
#         exec 2>"{log}"
#         export JUPYTER_PLATFORM_DIRS=1
#         mike serve --config-file {input.mkdocs_yml}
#         """


rule docs_serve:
    """
    Make and serve the documentation.
    NOTE: This rule is "blocking", and will not return until the server is stopped.
          This rule is only for development purposes.
    """
    localrule: True
    input:
        # WORKFLOW_BASE is used here instead of workflow.source_path()
        # since workflow.source_path() cannot cache an entire directory
        # so instead just point to the mkdocs.yml file and assume the
        # worker has access to the entire directory
        mkdocs_yml=WORKFLOW_BASE / "../docs/mkdocs.yml",
        dag_svg=rules.dag_svg.output,
    log:
        stdout=LOG_DIR / "docs_serve" / "stdout.log",
        stderr=LOG_DIR / "docs_serve" / "stderr.log",
    params:
        docs_assets=Path(config["DOCS_ASSETS_DIR"]).resolve(),
    conda:
        get_localized_conda(config["CONDA"]["ENVS"]["DOCS"])
    shell:
        """
        exec 1>"{log.stdout}"
        exec 2>"{log.stderr}"
        export JUPYTER_PLATFORM_DIRS=1
        export DOCS_ASSETS_DIR="{params.docs_assets}"
        mkdocs serve \
          --config-file {input.mkdocs_yml}
        """
