__use_yte__: true
__definitions__:
  - from pathlib import Path
  - |
    def existing_configfiles(candidates):
        return [candidate for candidate in candidates if Path(candidate).is_file()]
__variables__:
  configfile_candidates:
    - "config/config.yaml"
    # Load the local configuration file if it exists
    - "config/config.local.yaml"

# This SLURM snakemake profile is for running snakemake
# on a HPC cluster with SLURM as scheduler.

# TODO-copier-package update configuration for SLURM

# Hardware configuration
cores: 4

# Conda configuration
software-deployment-method: conda
use-conda: true

# Configuration files
?if existing_configfiles(configfile_candidates):
  configfile: ?existing_configfiles(configfile_candidates)
  # TODO-copier-etl add SLURM config files
