name: release
on:
  push:
    tags: ['v*']
permissions:
  contents: read
  # For OIDC for PyPI upload
  id-token: write

jobs:
  call-build-and-publish:
    uses: ./.github/workflows/build.yml
    with:
      publish: false
    # Configure this to publish to PyPI
    #   publish: true
    # secrets:
    #   PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
